### ISSUE TITLE
Game socket stays connected when user leaves game page

### ISSUE THREAD

**Issue by BearAlliance** [BearAlliance/pointing-poker#68]

**Comment by olore** [comment]
I have an idea for this

**Comment by olore** [comment]
So, when you navigate away to another site, like google or another host, the server gets the following:

```
[server] game 5177: player bbbb disconnecting. Code 1001:Remote peer is going away
```

I'm guessing that the "user leaves game page" means they go to another page on our site? and that is handled by react router... so we should call a socket.close when we change routes (I think). How's that sound @BearAlliance ?

**Comment by BearAlliance** [comment]
Yes I should have been more clear. 

“Leaves the route”

We just need to close the socket when the game page component unmounts. You can return a function from `useEffect` that does this

**Comment by olore** [comment]
I found this `import { useLocation } from 'react-router-dom';`
via https://reacttraining.com/blog/react-router-v5-1/#uselocation

But it seems I would want this in App.js and pay attention to when the route changes away from `/game/nnn` then close the socket. However I am not sure I want the socket created in App.js and then passed down... seems less than ideal.

We are calling `new WebSocketClient` in game-page.jsx, I'm thinking there is a better way to do it so that it acts more like a singleton and we can just import it from anywhere, like we do with state.js on the serverside.

**Comment by BearAlliance** [comment]
It's even more simple than that.

You can return a function from `useState` that will execute before the component is unmounted. react-router will destroy the component for us when we leave the route that renders that tree, so it'll fire automatically when the route changes

https://reactjs.org/docs/hooks-effect.html#effects-with-cleanup
